services:
  algohelper-frontend:
    build: ./frontend
    container_name: algohelper-frontend
    ports:
      - "3000:3000"
    depends_on:
      - algohelper-backend
  
  algohelper-backend:
    build: ./backend
    container_name: algohelper-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - algohelper-mongo

  algohelper-mongo:
    image: mongo:latest
    container_name: algohelper-mongo
    ports:
      - "27017:27017"